version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3.9-management
    container_name: rabbitmq
    ports:
      - "5672:5672"  # Порт для RabbitMQ
      - "15672:15672"  # Порт для управления RabbitMQ (Web UI)
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notification_network

  gateway:
    build: .
    container_name: gateway
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - rabbitmq
    networks:
      - notification_network

  email_service:
    build: .
    container_name: email_service
    command: python email_notification_app/email_app.py
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - notification_network

  telegram_service:
    build: .
    container_name: telegram_service
    command: python tg_notification_app/telegram_app.py
    env_file:
      - .env
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - notification_network

networks:
  notification_network:
    driver: bridge